import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const _doc = (id: string) => ({
  type: "doc",
  id,
});

const _category = (label: string, docIds: string[] = []) => ({
  label,
  type: "category",
  items: docIds.map((id) => _doc(id)),
});

const sidebars = {
  docsSidebar: [
    _category("Getting Started", ["what-youll-be-making", "inventory"]),
    // _doc("3d-printing-parts-and-slicing"),
    _category("PCB Assembly", [
      "general-tips",
      // "assemble-battery-pack",
      // "power-up",
      // "boot-the-microcontroller",
      // "make-some-noise",
      // "add-game-inputs",
      // "control-difficulty",
      // "prep-for-hacking",
    ]),
    // _category("Assembly and Care", ["final-assembly", "care"]),
    _category("Appendix", [
      // "bom",
      "pcb-troubleshooting",
      // "opening-the-enclosure",
      // "schematics",
      // "source-and-license",
    ]),
  ],
};

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

export default sidebars;
