import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const _doc = (id: string) => ({
  type: "doc",
  id,
});

const _category = (label: string, docIds: string[] = []) => ({
  label,
  type: "category",
  items: docIds.map((id) => _doc(id)),
});

const sidebars = {
  docsSidebar: [
    _category("Getting Started", ["what-youll-be-making", "inventory"]),
    _doc("3d-printing-parts-and-slicing"),
    _category("PCB Assembly", [
      "general-tips",
      "power-up",
      "lights-on",
      "cycle-lights",
      "stop-light-cycle",
      "sound-on",
      "pew-pew-pew",
    ]),
    _category("Final Assembly", [
      "prepare-3d-prints",
      "ready-electronics",
      "assemble-enclosure",
    ]),
    _category("Appendix", [
      "how-to-use-your-space-dice",
      "care",
      "bom",
      "pcb-troubleshooting",
      "assembly-troubleshooting",
      "opening-the-enclosure",
      "schematic",
      "source-and-license",
    ]),
  ],
};

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

export default sidebars;
